name: eyflutter_webview
description: eyflutter_webview
version: 2.0.5
homepage: https://github.com/eyinfo/eyflutter_webview

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  csslib: '>=0.17.0 <1.0.0'
  flutter_layout_grid: '>=1.0.1 <2.0.0'
  video_player: '>=2.1.1 <3.0.0'
  chewie: '>=1.0.0 <2.0.0'
  chewie_audio: '>=1.2.0 <2.0.0'
  flutter_svg: '>=0.22.0 <1.0.0'
  flutter_math_fork: '>=0.3.2+1 <1.0.0'
  collection: '>=1.15.0 <2.0.0'
  numerus: '>=1.1.1 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.webviewflutter
        pluginClass: WebViewFlutterPlugin
      ios:
        pluginClass: FLTWebViewFlutterPlugin
